# Generated by Django 6.0.7 on 2026-07-22 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo del simulacro (ej. Primer Simulacro de Admisión).', max_length=150)),
                ('fecha', models.DateField(help_text='Fecha programada en que se rinde el simulacro.')),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=400.0, help_text='Puntaje total máximo alcanzable en la prueba.', max_digits=6)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el simulacro está activo y visible en el sistema.')),
                ('descripcion', models.TextField(blank=True, help_text='Notas o instrucciones adicionales del examen.', null=True)),
            ],
            options={
                'verbose_name': 'Simulacro',
                'verbose_name_plural': 'Simulacros',
            },
        ),
        migrations.CreateModel(
            name='ResultadoSimulacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Puntaje total final acumulado.', max_digits=6)),
                ('respuestas_correctas', models.PositiveIntegerField(default=0, help_text='Cantidad de respuestas correctas.')),
                ('respuestas_incorrectas', models.PositiveIntegerField(default=0, help_text='Cantidad de respuestas incorrectas.')),
                ('respuestas_omitidas', models.PositiveIntegerField(default=0, help_text='Cantidad de preguntas no contestadas u omitidas.')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de registro de la prueba.')),
                ('alumno', models.ForeignKey(help_text='Alumno que rindió la evaluación.', limit_choices_to={'rol': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_simulacros', to=settings.AUTH_USER_MODEL)),
                ('simulacro', models.ForeignKey(help_text='Simulacro evaluado.', on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='simulacros.simulacro')),
            ],
            options={
                'verbose_name': 'Resultado de Simulacro',
                'verbose_name_plural': 'Resultados de Simulacros',
                'unique_together': {('alumno', 'simulacro')},
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pregunta', models.PositiveIntegerField(help_text='Número correlativo de la pregunta dentro del examen.')),
                ('enunciado', models.TextField(help_text='Enunciado de la pregunta en texto plano.')),
                ('alternativa_a', models.TextField(help_text='Opción A de la pregunta.')),
                ('alternativa_b', models.TextField(help_text='Opción B de la pregunta.')),
                ('alternativa_c', models.TextField(help_text='Opción C de la pregunta.')),
                ('alternativa_d', models.TextField(help_text='Opción D de la pregunta.')),
                ('alternativa_e', models.TextField(blank=True, help_text='Opción E de la pregunta (opcional para exámenes de 4 alternativas).', null=True)),
                ('alternativa_correcta', models.CharField(choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D'), ('E', 'Alternativa E')], help_text='Alternativa válida que se considera respuesta correcta.', max_length=1)),
                ('puntaje_correcta', models.DecimalField(decimal_places=2, default=4.0, help_text='Puntaje obtenido por contestar correctamente.', max_digits=5)),
                ('puntaje_incorrecta', models.DecimalField(decimal_places=2, default=-1.0, help_text='Puntaje (penalización) obtenido por contestar incorrectamente.', max_digits=5)),
                ('puntaje_omitida', models.DecimalField(decimal_places=2, default=0.0, help_text='Puntaje obtenido por omitir la pregunta.', max_digits=5)),
                ('simulacro', models.ForeignKey(help_text='Simulacro al que pertenece esta pregunta.', on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='simulacros.simulacro')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'unique_together': {('simulacro', 'numero_pregunta')},
            },
        ),
        migrations.CreateModel(
            name='DetalleRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa_marcada', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('O', 'Omitida')], default='O', help_text='Alternativa seleccionada por el estudiante.', max_length=1)),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0.0, help_text='Puntaje calculado obtenido para esta pregunta.', max_digits=5)),
                ('pregunta', models.ForeignKey(help_text='Pregunta que se está respondiendo.', on_delete=django.db.models.deletion.CASCADE, to='simulacros.pregunta')),
                ('resultado', models.ForeignKey(help_text='Encabezado del resultado al que pertenece este detalle.', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='simulacros.resultadosimulacro')),
            ],
            options={
                'verbose_name': 'Detalle de Respuesta',
                'verbose_name_plural': 'Detalles de Respuestas',
                'unique_together': {('resultado', 'pregunta')},
            },
        ),
    ]
