# Generated by Django 6.0.7 on 2026-07-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacro',
            name='area_academica',
            field=models.CharField(choices=[('INGENIERIAS', 'Ingenierías'), ('BIOMEDICAS', 'Biomédicas'), ('SOCIALES', 'Sociales')], default='INGENIERIAS', help_text='Área académica asociada al simulacro.', max_length=20),
        ),
    ]
