# Generated by Django 6.0.7 on 2026-08-23 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacros', '0002_simulacro_area_academica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacro',
            name='docente',
            field=models.ForeignKey(blank=True, help_text='Docente que programó o elaboró el simulacro.', limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulacros_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
