# Generated by Django 6.0.7 on 2026-07-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, help_text='Documento Nacional de Identidad (8 dígitos).', max_length=8, null=True, unique=True),
        ),
    ]
