# Generated by Django 6.0.7 on 2026-07-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_usuario_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='area_academica',
            field=models.CharField(blank=True, choices=[('INGENIERIAS', 'Ingenierías'), ('BIOMEDICAS', 'Biomédicas'), ('SOCIALES', 'Sociales')], help_text='Área académica obligatoria para Alumnos.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='curso_asignado',
            field=models.CharField(blank=True, help_text='Curso principal asignado al docente.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='precio_hora',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio por hora de dictado del docente.', max_digits=6),
        ),
    ]
