# Generated by Django 6.0.7 on 2026-07-30 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_asistenciadocente'),
        ('autenticacion', '0003_usuario_area_academica_usuario_curso_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ciclo',
            field=models.ForeignKey(blank=True, help_text='Ciclo académico al que pertenece el usuario (especialmente Docente).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='academico.ciclo'),
        ),
    ]
