# Generated by Django 6.0.7 on 2026-08-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_usuario_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador / Director'), ('SECRETARIA', 'Secretaría'), ('DOCENTE', 'Docente'), ('ALUMNO', 'Alumno')], default='ALUMNO', help_text='Rol asignado al usuario dentro de la academia.', max_length=20),
        ),
    ]
