# Generated by Django 6.0.7 on 2026-07-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, help_text='Fecha del registro de asistencia.')),
                ('hora_acceso', models.TimeField(auto_now_add=True, help_text='Hora exacta del escaneo y acceso.')),
                ('codigo_qr_escaneado', models.CharField(help_text='Identificador único o token desencriptado del código QR escaneado.', max_length=255)),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('TARDE', 'Tarde'), ('FALTA', 'Falta')], default='PRESENTE', help_text='Estado de la asistencia calculada al momento del ingreso.', max_length=15)),
            ],
            options={
                'verbose_name': 'Asistencia QR',
                'verbose_name_plural': 'Asistencias QR',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Identificador único del aula (ej. Aula 101, Salón B).', max_length=50, unique=True)),
                ('capacidad', models.PositiveIntegerField(default=40, help_text='Capacidad máxima de alumnos permitidos en el aula.')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del equipamiento o ubicación del aula.', null=True)),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del ciclo académico (ej. Ordinario 2026-I).', max_length=100)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio oficial del ciclo.')),
                ('fecha_fin', models.DateField(help_text='Fecha de finalización programada del ciclo.')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el ciclo está activo actualmente para matrículas o dictado.')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales sobre el ciclo.', null=True)),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_matricula', models.CharField(help_text='Código único de matrícula generado para el alumno.', max_length=20, unique=True)),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exactas en que se registró la matrícula.')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la matrícula se encuentra vigente.')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
    ]
