# Generated by Django 6.0.7 on 2026-07-22 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaqr',
            name='alumno',
            field=models.ForeignKey(help_text='Alumno asociado al registro de asistencia.', limit_choices_to={'rol': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_qr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matricula',
            name='alumno',
            field=models.ForeignKey(help_text='Alumno que realiza la matrícula.', limit_choices_to={'rol': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matricula',
            name='aula',
            field=models.ForeignKey(blank=True, help_text='Aula física asignada al alumno para sus clases presenciales.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas', to='academico.aula'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ciclo',
            field=models.ForeignKey(help_text='Ciclo de preparación al que se inscribe el alumno.', on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='academico.ciclo'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('alumno', 'ciclo')},
        ),
    ]
