# Generated by Django 6.0.7 on 2026-07-30 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, help_text='Fecha del registro de asistencia.')),
                ('hora_acceso', models.TimeField(auto_now_add=True, help_text='Hora exacta del escaneo.')),
                ('horas_dictadas', models.DecimalField(decimal_places=2, default=1.5, help_text='Horas de dictado validadas por Secretaría.', max_digits=4)),
                ('codigo_qr_escaneado', models.CharField(help_text='Token QR dinámico validado.', max_length=255)),
                ('docente', models.ForeignKey(help_text='Docente asociado al registro de asistencia.', limit_choices_to={'rol': 'DOCENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia Docente',
                'verbose_name_plural': 'Asistencias Docente',
            },
        ),
    ]
