# Generated by Django 6.0.7 on 2026-08-24 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_asistenciadocente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('MATRICULA', 'Matrícula'), ('PENSION_1', 'Pensión 1 (Mes 1)'), ('PENSION_2', 'Pensión 2 (Mes 2)'), ('PENSION_3', 'Pensión 3 (Mes 3)'), ('SIMULACRO', 'Derecho de Simulacro'), ('MATERIAL', 'Guías y Material'), ('OTRO', 'Otro Concepto')], default='MATRICULA', help_text='Concepto del cobro realizado.', max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto abonado en soles (S/.).', max_digits=8)),
                ('estado', models.CharField(choices=[('PAGADO', 'Pagado / Al día'), ('PENDIENTE', 'Pendiente / Deudor'), ('ANULADO', 'Anulado')], default='PAGADO', help_text='Estado del pago.', max_length=15)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('YAPE_PLIN', 'Yape / Plin'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', help_text='Forma de pago utilizada.', max_length=20)),
                ('numero_operacion', models.CharField(blank=True, help_text='Número de comprobante, ticket u operación bancaria.', max_length=50, null=True)),
                ('fecha_pago', models.DateField(help_text='Fecha en que se efectuó el pago.')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de registro en el sistema.')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones o notas adicionales.', null=True)),
                ('alumno', models.ForeignKey(help_text='Alumno asociado al pago o pensión.', limit_choices_to={'rol': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL)),
                ('ciclo', models.ForeignKey(blank=True, help_text='Ciclo académico correspondiente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='academico.ciclo')),
                ('registrado_por', models.ForeignKey(blank=True, help_text='Usuario de Secretaría o Administrador que registró el pago.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago y Pensión',
                'verbose_name_plural': 'Pagos y Pensiones',
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
    ]
